Pranav2612000/milaap

- src/views/Connection/Controls.js
> connection: send request to express server when connection ends.

- .vscode/settings.json
- package-lock.json
- package.json
- src/containers/DefaultLayout/DefaultAside.js
- src/containers/DefaultLayout/DefaultLayout.js
- src/views/Connection/Controls.js
- src/views/Rooms/Room.css
- src/views/Rooms/Rooms.js
Fixes #6
The implementation works almost perfectly. There is a slight stutter when order is changed. This can be fixed. However, I'm holding off on the solutions as we're planning plenty of changes to the structure and working of this file and the solution is very specific.
Will implement the fix once we near deployment.
> Drag n drop

- src/views/Connection/Controls.js
> Controls: Fixed buttons and added error on buttons

- src/containers/DefaultLayout/DefaultLayout.js
- src/containers/DefaultLayout/peerHandler.js
- src/views/Pages/Login/Login.js
- src/views/Pages/Login/login.scss
- src/views/Rooms/Rooms.js
Added Firebase Login.
User redirect to enter username not integrated
> Firebase Authentication

- src/containers/DefaultLayout/DefaultLayout.js
- src/views/Connection/Controls.js
- src/views/Dashboard/Dashboard.js
- src/views/MessageList/index.js
- src/views/Pages/Login/Login.js
- src/views/Pages/Register/Register.js
Solved Issue https://github.com/Pranav2612000/milaap/issues/19
> Dashboard : removed unnecessary backend calls

- src/views/Pages/Register/Register.js
solves https://github.com/Pranav2612000/milaap/issues/48
> added password match

- package-lock.json
- package.json
- src/containers/DefaultLayout/DefaultLayout.js
- src/containers/DefaultLayout/peerHandler.js
- src/firebaseConfig.js
- src/views/Pages/Login/Login.js
- src/views/Pages/Login/login.scss
- src/views/Rooms/Rooms.js
Please merge this branch with the master.
> Firebase Authentication added

- src/views/Connection/Controls.js
> Fix crash when ending call

- src/views/Connection/Controls.js
Reverts Pranav2612000/milaap#62
> Revert "Fix crash when ending call"

- package-lock.json
- package.json
- src/views/Connection/Controls.js
> video: Remove ended and closed streams from display.

- src/views/Connection/Controls.js
- src/views/Rooms/Room.css
- src/views/Rooms/Rooms.js
Allows full screen, audio control and PiP mode
> Room: allow html5 controls

- .vscode/settings.json
- src/views/Connection/Controls.js
- src/views/Rooms/Room.css
- src/views/Rooms/Rooms.js
> Controls: Video controls

- src/containers/DefaultLayout/DefaultAside.js
- src/containers/DefaultLayout/DefaultHeader.js
- src/containers/DefaultLayout/DefaultLayout.js
- src/scss/_variables.scss
- src/views/Compose/Compose.css
- src/views/Compose/index.js
- src/views/Message/index.js
- src/views/MessageList/index.js
- src/views/Rooms/Rooms.js
- src/views/Toolbar/index.js
- src/views/Widgets/MemberList.js
> CSS: Dark UI

- package.json
- src/views/Connection/Connect.js
- src/views/Connection/emmiter.js
- src/views/Rooms/Rooms.js
- yarn.lock
Things this PR will handle : 
* End call
* Close connection
* Handle error while connection
> End call implementation done

- backend/index.js
- backend/routes/user.js
- package-lock.json
- src/App.js
- src/config.js
- src/containers/DefaultLayout/DefaultAside.js
- src/containers/DefaultLayout/DefaultHeader.js
- src/containers/DefaultLayout/DefaultLayout.js
- src/containers/DefaultLayout/InnerHeader.js
- src/index.js
- src/redux/loginRedux/loginAction.js
- src/redux/loginRedux/loginReducer.js
- src/redux/registerRedux/registerAction.js
- src/redux/roomRedux/roomAction.js
- src/views/Compose/index.js
- src/views/Connection/Controls.js
- src/views/Dashboard/Dashboard.js
- src/views/MessageList/index.js
- src/views/Pages/Guest/Guest.js
- src/views/Widgets/MemberList.js
Now the username is taken from Redux-Store.
> removed backend calls for fetching usernames and a few styles added

- public/index.html
- src/containers/DefaultLayout/DefaultAside.js
- src/containers/DefaultLayout/DefaultHeader.js
- src/containers/DefaultLayout/DefaultLayout.css
- src/views/Compose/Compose.css
- src/views/Compose/index.js
- src/views/Connection/Controls.js
- src/views/Message/Message.css
- src/views/Message/index.js
- src/views/MessageList/MessageList.css
- src/views/MessageList/index.js
- src/views/Widgets/MemberList.css
Updated the collapsed logo on Dashboard
Matched the icons with dark theme
> Logos and CSS fixes

- src/views/Connection/Connect.js
- src/views/Rooms/Room.css
For "me", the elements are still created however, their display is set to none.
This is done to allow muteVideo function to with all video, if necessary,
> improvement: mute indicator below video

- src/views/Pages/Login/Login.js
- src/views/Pages/Register/Register.js
Added Loading indicators to Login and Register pages
> improvement: Loading status indicators

- src/views/Message/Message.css
> fix: long message/username overscroll

- public/index.html
- src/views/Compose/Compose.css
- src/views/Message/index.js
1. Changed default font currently to Proxima Nova.
2. Messages and username displayed together
> ui: Typography and chat ui

- src/views/Connection/Connect.js
Will provide for a better user experience and diagnosis if and when an issue occurs, especially on mobile devices.
> improvement: alert when browser rejects permission to media object
